# B站：神奇的布欧
# 微信：l1243278923

In [1]:
import numpy as np

# 创建数组

In [2]:
n1 = np.array([1, 2, 3])
n2 = np.array([0.1, 0.2, 0.3])
n3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print(n3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 自定义类型

In [6]:
list1 = [1, 2, 3]
n1 = np.array(list1, dtype=float)
print(n1)
print(f"数组类型：{n1.dtype}")
print("数组内元素类型：", type(n1[0]))

[1. 2. 3.]
数组类型：float64
数组内元素类型： <class 'numpy.float64'>


# 复制数组

In [7]:
n1 = np.array([1, 2, 3])
n2 = n1

In [8]:
n2[1] = 6
print(n1)
print(n2)

[1 6 3]
[1 6 3]


In [9]:
n1 = np.array([1, 2, 3])
n2 = np.array(n1, copy=True)
n2[1] = 7
print(n1)
print(n2)

[1 2 3]
[1 7 3]


# 修改数组维数

In [10]:
n1 = [1, 2, 3]
n2 = np.array(n1, ndmin=3)
print(n2)
print(n2.shape)

[[[1 2 3]]]
(1, 1, 3)


# 创建一个指定形状的未初始化的数组

In [12]:
n1 = np.empty([3, 3])
print(n1)

[[0.0e+000 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 8.2e-321]
 [0.0e+000 0.0e+000 0.0e+000]]


# 创建一个以0填充的数组

In [13]:
n1 = np.zeros([2, 3])
print(n1)

[[0. 0. 0.]
 [0. 0. 0.]]


# 创建一个以1填充的数组

In [14]:
n1 = np.ones([3, 3])
print(n1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 创建一个以指定数值填充的数组

In [15]:
n1 = np.full((3, 3), 10)
print(n1)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


# 数组的加减乘除运算

In [16]:
n1 = np.array([1, 2])
n2 = np.array([3, 4])
print(n1 + n2)

[4 6]


In [17]:
print(n1 - n2)

[-2 -2]


In [18]:
print(n1 * n2)

[3 8]


In [19]:
print(n1 / n2)

[0.33333333 0.5       ]


# 数组的reshape操作

In [20]:
n1 = np.array(
    ['唧', '唧', '复', '唧', '唧', '木', '兰', '当', '户', '织', '不', '闻', '机', '杼', '声', '惟', '闻', '女', '叹',
     '息'])

In [21]:
print(n1)

['唧' '唧' '复' '唧' '唧' '木' '兰' '当' '户' '织' '不' '闻' '机' '杼' '声' '惟' '闻' '女'
 '叹' '息']


In [22]:
print(n1.shape)

(20,)


In [23]:
n2 = n1.reshape(4, 5)
print(n2)

[['唧' '唧' '复' '唧' '唧']
 ['木' '兰' '当' '户' '织']
 ['不' '闻' '机' '杼' '声']
 ['惟' '闻' '女' '叹' '息']]


# 矩阵的创建

In [24]:
a = np.mat([[5, 6], [7, 8]])
b = np.mat([[1, 2], [3, 4]])
print(a)
print(b)

[[5 6]
 [7 8]]
[[1 2]
 [3 4]]


In [25]:
print(type(a))
print(type(b))

<class 'numpy.matrix'>
<class 'numpy.matrix'>


# 矩阵的加减乘除

In [26]:
data1 = np.mat([[1, 2], [3, 4], [5, 6]])
data2 = np.mat([1, 2])
data3 = np.mat([[5, 6], [7, 8]])
print(data1 + data2)
print(data1 - data2)
print(data1 / data2)

[[2 4]
 [4 6]
 [6 8]]
[[0 0]
 [2 2]
 [4 4]]
[[1. 1.]
 [3. 2.]
 [5. 3.]]


In [28]:
print(data1 * data3)

[[19 22]
 [43 50]
 [67 78]]


# 数组点乘运算

In [29]:
n1 = np.array([1, 2, 3])
n2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(np.multiply(n1, n2))

[[1 4 9]
 [1 4 9]
 [1 4 9]]


# 矩阵转置

In [32]:
n1 = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始矩阵：\n", n1)
print("转置：\n", n1.T)

原始矩阵：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
转置：
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


# 矩阵求逆

In [33]:
n1 = np.mat([[1, 3, 3], [4, 5, 6], [7, 15, 9]])
print("原始矩阵：\n", n1)
print("转置：\n", n1.I)

原始矩阵：
 [[ 1  3  3]
 [ 4  5  6]
 [ 7 15  9]]
转置：
 [[-0.9375      0.375       0.0625    ]
 [ 0.125      -0.25        0.125     ]
 [ 0.52083333  0.125      -0.14583333]]


# 使用Numpy内置函数进行数组加减乘除

In [34]:
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n2 = np.array([10, 10, 10])
print(np.add(n1, n2))

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [35]:
print(np.subtract(n1, n2))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


In [36]:
print(np.multiply(n1, n2))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [37]:
print(np.divide(n1, n2))

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


# 幂运算

In [38]:
n1 = np.array([10, 100, 1000])
print(np.power(n1, 3))

[      1000    1000000 1000000000]


# 数组元素的行列求和

In [39]:
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("对数组元素求和：")
print(n1.sum())

对数组元素求和：
45


In [41]:
print(n1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# 列求和
print(n1.sum(axis=0))

[12 15 18]


In [42]:
# 行求和
print(n1.sum(axis=1))

[ 6 15 24]


# 平均值

In [43]:
# 整体平均值
print(n1.mean())
# 列平均值
print(n1.mean(axis=0))
# 行平均值
print(n1.mean(axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


# 最大值最小值

In [44]:
# 最大值
print(n1.max())

9


In [45]:
# 组小值
print(n1.min())

1


In [46]:
print(n1.max(axis=0))
print(n1.max(axis=1))

[7 8 9]
[3 6 9]


In [47]:
print(n1.min(axis=0))
print(n1.min(axis=1))

[1 2 3]
[1 4 7]


# 求中位数

In [48]:
n1 = np.array([34.5, 36, 37.8, 39, 39.8, 33.6])
sort_n = np.sort(n1)

In [49]:
print(sort_n)

[33.6 34.5 36.  37.8 39.  39.8]


In [50]:
# 中位数
print(np.median(sort_n))

36.9


# 方差和标准差

In [51]:
n1 = np.array([34.5, 36, 37.8, 39, 39.8, 33.6])
# 方差
print(np.var(n1))

5.168055555555551


In [52]:
# 标准差
print(np.std(n1))

2.2733357771247853


# 数组排序

In [53]:
n1 = np.array([[4, 7, 3], [2, 8, 5], [9, 1, 6]])
print(np.sort(n1))

[[3 4 7]
 [2 5 8]
 [1 6 9]]


In [54]:
print(np.sort(n1, axis=1))

[[3 4 7]
 [2 5 8]
 [1 6 9]]


In [55]:
print(np.sort(n1, axis=0))

[[2 1 3]
 [4 7 5]
 [9 8 6]]
