# B站：神奇的布欧
# 微信：l1243278923

In [1]:
import torch

# 判断GPU是否可用

In [2]:
torch.cuda.is_available()

True

# 张量

# 默认类型float32

In [3]:
tensor1 = torch.Tensor(5)
print(tensor1.dtype)

torch.float32


# 更改张量默认类型

In [4]:
torch.set_default_tensor_type(torch.FloatTensor)

D:\software_code\Anaconda\envs\pytorchpy39\lib\site-packages\torch\__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\tensor\python_tensor.cpp:453.)
  _C._set_default_tensor_type(t)


# 获取默认数据类型

In [5]:
torch.get_default_dtype()

torch.float32

# 初始化张量

In [6]:
tensor2 = torch.Tensor([[1, 2], [3, 4]])
print(tensor2)

tensor([[1., 2.],
        [3., 4.]])


# 通个传入数组初始化张量

In [7]:
import numpy as np

In [8]:
array = np.array([[5, 6], [7, 8]])

In [9]:
tensor3 = torch.Tensor(array)

In [10]:
print(tensor3)

tensor([[5., 6.],
        [7., 8.]])


# 按类型初始化

In [11]:
tensor1 = torch.DoubleTensor([2])
tensor2 = torch.IntTensor([4])

In [12]:
print(tensor1)

tensor([2.], dtype=torch.float64)


In [13]:
print(tensor2)

tensor([4], dtype=torch.int32)


# 构造全0全1张量

In [14]:
zeroTensor = torch.zeros([3, 6], dtype=torch.float32)

In [15]:
print(zeroTensor)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [16]:
zeroTensor

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [17]:
print(type(zeroTensor[0]))

<class 'torch.Tensor'>


In [18]:
oneTensor = torch.ones([3, 6], dtype=torch.int32)

In [19]:
oneTensor

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int32)

# 创建相同大小的全0张量

In [20]:
tensor1 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
linkzero = torch.zeros_like(tensor1)
print(tensor1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [21]:
print(linkzero)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 生成同纬度随机张量

In [22]:
tensor1 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
randtensor = torch.rand_like(tensor1)

In [23]:
print(randtensor)

tensor([[0.8637, 0.9292, 0.0826],
        [0.9570, 0.1293, 0.6126]])


# 自定义值填充

In [24]:
newfull = tensor1.new_full((3, 3), fill_value=8)
print(newfull)

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])


In [25]:
newzero = tensor1.new_zeros((3, 3))
print(newzero)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


# 张量的类型转换

In [26]:
tensor1 = torch.Tensor([1, 2, 3])
print(tensor1.dtype)

torch.float32


In [27]:
print(tensor1.int().dtype)

torch.int32


In [28]:
print(tensor1.to(dtype=torch.int32).dtype)

torch.int32


# 获取张量的值

In [29]:
tensor1[0].item()

1.0

# 张量转换到数组

In [30]:
array = tensor1.numpy()

In [31]:
array

array([1., 2., 3.], dtype=float32)

# 数组转换为张量

In [32]:
array = np.ones((3, 3))

In [33]:
tensor1 = torch.as_tensor(array)

In [34]:
tensor1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [35]:
tensor2 = torch.from_numpy(array)

In [36]:
tensor2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# 通过指定的均值和标准差生成随机数

In [37]:
torch.manual_seed(456)
a = torch.normal(mean=0, std=torch.tensor(1.0))
print(a)

tensor(-2.4306)


# 生成0-50随机排列的张量

In [38]:
tensor1 = torch.randperm(50)

In [39]:
print(tensor1)

tensor([ 4, 32, 30, 12, 37, 13, 38, 41,  1, 49, 47, 15, 29, 20, 21, 48, 17, 11,
        23, 45, 24, 27,  8,  5,  9, 34,  2,  3, 10, 43, 22, 18, 14, 40, 42, 26,
        44, 19, 16, 46, 36, 31, 28, 33,  0,  7, 25,  6, 39, 35])


# 生成指定范围指定步长的张量

In [40]:
tensor1 = torch.arange(start=0, end=100, step=5)
print(tensor1)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])


# 使用linspace生成固定数量等间隔的张量

In [41]:
tensor1 = torch.linspace(start=0, end=100, steps=10)

In [42]:
tensor1

tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])

# 获取张量维度

In [43]:
print(tensor1.shape)

torch.Size([10])


In [44]:
print(tensor1.size())

torch.Size([10])


# 计算张量中元素个数

In [45]:
tensor1.numel()

10

# reshape改变张量的形状

In [46]:
tensor1 = torch.arange(15)
tensor2 = tensor1.reshape(5, 3)
print(tensor1)
print(tensor2)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])


# resize

In [47]:
tensor2 = tensor1.resize(3, 5)

D:\software_code\Anaconda\envs\pytorchpy39\lib\site-packages\torch\_tensor.py:836: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [48]:
print(tensor2)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


# 升维降维

In [49]:
print(tensor1.shape)

torch.Size([15])


In [50]:
tensor1 = torch.unsqueeze(tensor1, dim=0)
print(tensor1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])


In [51]:
print(tensor1.shape)

torch.Size([1, 15])


In [52]:
tensor1 = torch.squeeze(tensor1, dim=0)

In [53]:
print(tensor1.shape)

torch.Size([15])


In [54]:
print(tensor1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


# 张量的筛选操作

In [55]:
tensor1 = torch.randperm(12).reshape(3, 4)
tensor2 = -tensor1
print(tensor1)
print(tensor2)

tensor([[ 1,  9,  5,  2],
        [ 3,  8, 10,  7],
        [ 0,  6,  4, 11]])
tensor([[ -1,  -9,  -5,  -2],
        [ -3,  -8, -10,  -7],
        [  0,  -6,  -4, -11]])


In [56]:
tensor3 = torch.where(tensor1 > 6, tensor1, tensor2)

In [57]:
print(tensor3)

tensor([[-1,  9, -5, -2],
        [-3,  8, 10,  7],
        [ 0, -6, -4, 11]])


# 张量的拼接和拆分

In [58]:
tensor1 = torch.randperm(12).reshape(3, 4)
tensor2 = torch.linspace(0, 50, 12).reshape(3, 4)
tensor3 = torch.cat((tensor1, tensor2), dim=0)

In [59]:
print(tensor1)
print(tensor2)
print(tensor3)

tensor([[ 8,  3,  9,  1],
        [ 7,  2, 11,  6],
        [10,  0,  4,  5]])
tensor([[ 0.0000,  4.5455,  9.0909, 13.6364],
        [18.1818, 22.7273, 27.2727, 31.8182],
        [36.3636, 40.9091, 45.4545, 50.0000]])
tensor([[ 8.0000,  3.0000,  9.0000,  1.0000],
        [ 7.0000,  2.0000, 11.0000,  6.0000],
        [10.0000,  0.0000,  4.0000,  5.0000],
        [ 0.0000,  4.5455,  9.0909, 13.6364],
        [18.1818, 22.7273, 27.2727, 31.8182],
        [36.3636, 40.9091, 45.4545, 50.0000]])


In [60]:
tensor4 = torch.cat((tensor1, tensor2), dim=1)

In [61]:
print(tensor4)

tensor([[ 8.0000,  3.0000,  9.0000,  1.0000,  0.0000,  4.5455,  9.0909, 13.6364],
        [ 7.0000,  2.0000, 11.0000,  6.0000, 18.1818, 22.7273, 27.2727, 31.8182],
        [10.0000,  0.0000,  4.0000,  5.0000, 36.3636, 40.9091, 45.4545, 50.0000]])


# 沿新维度拼接张量（stack）

In [62]:
tensor1 = torch.randperm(12).reshape(3, 4)
tensor2 = torch.linspace(0, 50, 12).reshape(3, 4)
tensor3 = torch.stack((tensor1, tensor2), dim=0)

In [63]:
print(tensor3)

tensor([[[ 8.0000, 11.0000,  7.0000,  3.0000],
         [ 9.0000,  4.0000,  5.0000, 10.0000],
         [ 2.0000,  6.0000,  1.0000,  0.0000]],

        [[ 0.0000,  4.5455,  9.0909, 13.6364],
         [18.1818, 22.7273, 27.2727, 31.8182],
         [36.3636, 40.9091, 45.4545, 50.0000]]])


In [64]:
tensor4 = torch.stack((tensor1, tensor2), dim=1)
print(tensor4)

tensor([[[ 8.0000, 11.0000,  7.0000,  3.0000],
         [ 0.0000,  4.5455,  9.0909, 13.6364]],

        [[ 9.0000,  4.0000,  5.0000, 10.0000],
         [18.1818, 22.7273, 27.2727, 31.8182]],

        [[ 2.0000,  6.0000,  1.0000,  0.0000],
         [36.3636, 40.9091, 45.4545, 50.0000]]])


# CPU 、 GPU转换

In [65]:
tensor1 = torch.Tensor([3,5])

In [66]:
print(tensor1)

tensor([3., 5.])


In [67]:
print(tensor1.is_cuda)

False


In [68]:
print(tensor1.device)

cpu


In [69]:
tensor1 = tensor1.to("cuda")

In [70]:
print(tensor1.is_cuda)

True


In [71]:
print(tensor1.device)

cuda:0


# 逐元素比较是否相等

In [72]:
tensor1 = torch.Tensor([i for i in range(10)])
tensor2 = torch.arange(0, 10)
tensor3 = torch.unsqueeze(tensor2, dim=0)
print(tensor1)
print(tensor2)
print(tensor3)
print(torch.eq(tensor1, tensor2))
print(torch.eq(tensor1, tensor3))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([True, True, True, True, True, True, True, True, True, True])
tensor([[True, True, True, True, True, True, True, True, True, True]])


# 判断张量是否具有相同的形状

In [73]:
tensor1 = torch.Tensor([i for i in range(10)])
tensor2 = torch.arange(0, 10)
tensor3 = torch.unsqueeze(tensor2, dim=0)
print(tensor1)
print(tensor2)
print(tensor3)
print(torch.equal(tensor1, tensor2))
print(torch.equal(tensor1, tensor3))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
True
False


# 张量的幂

In [74]:
tensor1 = torch.Tensor([i for i in range(10)])
print(torch.pow(tensor1, 3))

tensor([  0.,   1.,   8.,  27.,  64., 125., 216., 343., 512., 729.])


In [75]:
print(tensor1 ** 2)

tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


# 指数、对数、平方根

In [76]:
tensor1 = torch.Tensor([i for i in range(10)])
print(tensor1)
print(torch.exp(tensor1))
print(torch.log(tensor1))
print(torch.sqrt(tensor1))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03])
tensor([  -inf, 0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794,
        2.1972])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284,
        3.0000])


# 张量的剪裁

In [77]:
tensor1 = torch.Tensor([i for i in range(10)]).reshape(2, 5)
print(tensor1)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])


In [81]:
# 根据最大值剪裁
print(torch.clamp_max(tensor1, 6))
# 根据最小值剪裁
print(torch.clamp_min(tensor1, 6))
# 指定范围剪裁
print(torch.clamp(tensor1, 2, 8))

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 6., 6., 6.]])
tensor([[6., 6., 6., 6., 6.],
        [6., 6., 7., 8., 9.]])
tensor([[2., 2., 2., 3., 4.],
        [5., 6., 7., 8., 8.]])


# 矩阵操作

In [82]:
tensor1 = torch.rand(4, 4) * 10
tensor2 = torch.randperm(8).reshape(4, 2).float()
print(tensor1)
print(tensor2)

tensor([[4.3375, 2.6885, 5.7688, 5.2385],
        [1.3120, 1.8621, 9.1318, 9.3914],
        [2.6798, 4.3571, 8.8020, 0.6380],
        [6.6586, 4.8916, 7.9220, 9.1864]])
tensor([[4., 3.],
        [7., 6.],
        [2., 1.],
        [5., 0.]])


In [84]:
# 转置
print(torch.t(tensor1))
# 矩阵的逆
print(torch.inverse(tensor1))

tensor([[4.3375, 1.3120, 2.6798, 6.6586],
        [2.6885, 1.8621, 4.3571, 4.8916],
        [5.7688, 9.1318, 8.8020, 7.9220],
        [5.2385, 9.3914, 0.6380, 9.1864]])
tensor([[ 0.7520, -0.1466, -0.0957, -0.2723],
        [-1.1920, -0.0422,  0.1860,  0.7100],
        [ 0.3783,  0.0599,  0.0563, -0.2809],
        [-0.2365,  0.0771, -0.0783,  0.1704]])


In [85]:
# 矩阵乘法
print(tensor1.matmul(tensor2))

tensor([[ 73.8996,  34.9124],
        [ 83.5039,  24.2408],
        [ 62.0132,  42.9843],
        [122.6517,  57.2475]])


# 统计计算

In [86]:
tensor1 = torch.randperm(10)
print(tensor1)

tensor([6, 8, 1, 2, 4, 5, 9, 0, 7, 3])


In [87]:
print(tensor1.max())

tensor(9)


In [88]:
print(tensor1.min())

tensor(0)


In [89]:
print(tensor1.argmax())

tensor(6)


In [90]:
print(tensor1.argmin())

tensor(7)


# 排序

In [91]:
tensor1 = torch.randperm(10)
print(tensor1)

tensor([9, 0, 7, 1, 4, 5, 8, 2, 6, 3])


In [92]:
# 升序
print(torch.sort(tensor1, descending=False))

torch.return_types.sort(
values=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
indices=tensor([1, 3, 7, 9, 4, 5, 8, 2, 6, 0]))


In [93]:
# 降序
print(torch.sort(tensor1, descending=True))

torch.return_types.sort(
values=tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
indices=tensor([0, 6, 2, 8, 5, 4, 9, 7, 3, 1]))


# 二维张量排序

In [94]:
tensor1 = torch.randperm(16).reshape(4, 4)
print(tensor1)
print(torch.sort(tensor1))

tensor([[ 8,  4,  2,  3],
        [ 7,  0, 12, 11],
        [14, 15,  9,  6],
        [ 1, 10,  5, 13]])
torch.return_types.sort(
values=tensor([[ 2,  3,  4,  8],
        [ 0,  7, 11, 12],
        [ 6,  9, 14, 15],
        [ 1,  5, 10, 13]]),
indices=tensor([[2, 3, 1, 0],
        [1, 0, 3, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 3]]))


# 平均值

In [96]:
tensor1 = torch.randperm(16).reshape(4, 4).to(dtype=torch.float64)
print(torch.mean(tensor1, dim=1, keepdim=True))

tensor([[10.5000],
        [ 5.5000],
        [ 5.2500],
        [ 8.7500]], dtype=torch.float64)


In [97]:
print(torch.mean(tensor1, dim=0, keepdim=True))

tensor([[7.0000, 6.7500, 7.7500, 8.5000]], dtype=torch.float64)
